### ISSUE TITLE
Don't use val() in the field method, otherwise it will always return the same value.

### ISSUE THREAD

**Issue by nomemory** [cdelmonte-zg/kafka-streams-demo#1]
https://github.com/cdelmonte-zg/kafka-streams-demo/blob/422df27e90a1ad5ec0e640166d3a89e4d8bb8ea9/afs-data-generator/src/main/java/de/cdelmonte/afs/datagenerator/mocker/MocksGenerator.java#L63

**Comment by cdelmonte-zg** [comment]
Thank you, fixed
